#!/usr/bin/env php
<?php

use Symfony\Component\Console\Application;

/* The console directory should be moved to your document root */
$composer_autoload = dirname(__DIR__) . "/vendor/autoload.php";
require_once($composer_autoload);

$kernel = new \GenerCodeSlim\GenerCodeKernel(dirname(__DIR__, 2));
$container = $kernel->load();


$app = new Application();
$app->add(new \GenerCodeCmd\DictionaryCommand($container));
$app->add(new \GenerCodeCmd\DownloadCommand($container));
$app->add(new \GenerCodeCmd\MigrationCommand($container));
$app->add(new \GenerCodeCmd\PublishCommand($container));
$app->add(new \GenerCodeCmd\UploadCommand($container));
$app->add(new \GenerCodeCmd\CdnCommand($container));
$app->add(new \GenerCodeCmd\QueueWorkerCommand($container));

$listen = new \Illuminate\Queue\Console\ListenCommand();
$listen->setLaravel($container);
$app->add($listen);

$app->run();